- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2,db_and_web_server3
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=installed
      with_items:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python-pip
         - python-mysqldb

    - name: Install MySQL database
      apt: name={{ item }} state=installed
      with_items:
         - mysql-server
         - mysql-client

    - name: create MySQL configuration file
      copy:
        content: |
          [client]
          user=root
          password="Passw0rd"
        dest: "/root/.my.cnf"

    - name: Start MySQL database
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create application database
      mysql_db: name=employee_db state=present

    - name: Create datbase user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install Python Flask dependency
      pip:
        name: '{{ item }}'
        with_items:
          - flask
          - flask-mysql

    - name: Copy source code
      copy: src=app.py dest=/opt/app.py

    - name: Start Web server
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
